# Generated by Django 4.0.6 on 2023-11-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('job_publication_date', models.DateField(verbose_name='publication date')),
                ('job_subject_area', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_description', models.TextField(max_length=2000)),
                ('job_availability', models.BooleanField(default=False)),
            ],
        ),
    ]
