# Generated by Django 4.0.6 on 2023-11-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_model',
            fields=[
                ('Tel_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
